# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

baseurl: /blog
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
pygments: true
